apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-model-monitor
  labels:
    release: prom   # Match the label of your Prometheus instance as per Helm release
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default   # or your namespace
  endpoints:
    - port: metrics   # or match name of your service port
      path: /
      interval: 15s
      scrapeTimeout: 10s
